### ISSUE TITLE
dont know how to set this up

### ISSUE THREAD

**Issue by devansh7777** [anoop142/cowin-cli#1]
can you help me with setting this up. like on what software to run it on or something like that.

**Comment by anoop142** [comment]
1.Download pre compiled binary from download section 
2.Open powershell or command prompt in the same folder (windows)
3.run cowin-cli with specified parameters

**Comment by devansh7777** [comment]
@anoop142 what command am i supposed to use 
ps -i dont know anything about go language

**Comment by anoop142** [comment]
You don't need to know about the go language at all to use this.
You don't need go installed in your system!.
Download the executable from https://github.com/anoop142/cowin-cli/releases.
Extract .
use command prompt/ powershell to run it.
