### ISSUE TITLE
Unable to run cowin-cli in karnataka

### ISSUE THREAD

**Issue by siddkothari** [anoop142/cowin-cli#10]
Hey anoop, im a user from karnataka and im unable to run the precompiled version 1.4.7 and it shows tamilnadu and i want to run it in karnataka. Can you pls help ?

**Comment by anoop142** [comment]
Hi, right click on the 'cowin-cli-auto-book.bat' file and select edit using notepad, change the  required values , state, district, mobile number... etc and save the file.

**Comment by siddkothari** [comment]
Name means is it beneficiary name ?

**Comment by siddkothari** [comment]
![Uploading CAD11A59-9B07-4B22-AD4F-2B70AEB0274E.jpeg…]()

**Comment by anoop142** [comment]
> Name means is it beneficiary name ?

yes
