### ISSUE TITLE
Invalid District, Pincode (-p) returning with "Unauthenticed Access"

### ISSUE THREAD

**Issue by profhacker3** [anoop142/cowin-cli#11]
**$ cowin-cli -p 423701
2021/05/21 17:16:03 Unauthenticated access!**

Furthermore my district or pincode not working.

**$ cowin-cli -s maharashtra -d aurangabad
2021/05/21 17:20:43 Invalid district!**

I am on "Termux" with Zero Coding Knowledge. Please help and how to notify/book by "Pincode"

**Comment by anoop142** [comment]
Hi ,
there are two reasons
1. Unauthenticated access is due tot the fact that cowin-cli always looks for slots for tomorrows's date, even though the cowin portal shows today's date slots , booking always happens for tomorrow,so you can ignore it.
2. server returns Aurangabad  as 'Aurangabad  ' , there is  a whitespace which confuses cowin-cli, which will be fixed soon.

**Comment by profhacker3** [comment]
Please can you tell, how to notify/book by "Pincode". Because I live in Taluka where I am only opt to put Pincode.

Thanks in advance brother

**Comment by anoop142** [comment]
listing by pin code no longer works without login , it will be removed in future version
what you can do is list by district and grep the output int the listing function to match a number of centers .

**Comment by profhacker3** [comment]
Okay I got it. Thankyou for such good work.
