### ISSUE TITLE
Entered two name ID's and it only booked for the first one

### ISSUE THREAD

**Issue by ad1tyas** [anoop142/cowin-cli#12]
![Capture](https://user-images.githubusercontent.com/6461000/119263016-ff0a1100-bbfa-11eb-937f-07595d426ec7.PNG)

So I tried this, I thought two ID's with a comma separation would work for booking ID 1 and 2 together, but the bot only booked for ID 1.
(I've used it earlier with 'all' in my bat file, which works fine to book everyone)

I'm going to have to cancel and have asked my friend to use a new number for only the two who need to be vaccinated, and try again tomorrow :(.

**Comment by anoop142** [comment]
I'll try to implement taking multiple user id as well as passing names separated by ','

**Comment by ad1tyas** [comment]
Ah it was never implemented. My bad. 

Yep, if you could implement that, it would be great!
