### ISSUE TITLE
Setup in MacOs

### ISSUE THREAD

**Issue by sahilamanu** [anoop142/cowin-cli#13]
Hello,
First of all thankyou for the awesome code.

1. I Setuped Go Lang
2. Ran first script to go get the repo.
3. after that when i try to list i am getting an error like --> `zsh: command not found: cowin-cli`

The Versions are here

- MacOs - 11.3.1
- Bash v.3.2

Kindly help, I am trying to get slots for Ernakulam, Thanks and Regards

**Comment by ad1tyas** [comment]
Run it from go\bin

**Comment by anoop142** [comment]
Hi,
Refer google to setup GOPATH in mac.
