### ISSUE TITLE
Merge PR 14

### ISSUE THREAD

**Issue by ad1tyas** [anoop142/cowin-cli#15]
Hey, could you merge this so the bot starts working again (without Chrome Inspect Token trickery)

https://github.com/anoop142/cowin-cli/pull/14

Thanks.

**Comment by anoop142** [comment]
merged and technically its not a bot lol

**Comment by ad1tyas** [comment]
Sorry xD.. 

Could you rebuild the Linux and Windows binaries?

**Comment by anoop142** [comment]
yeah
