### ISSUE TITLE
(Idea) Use token for listing centers

### ISSUE THREAD

**Issue by ad1tyas** [anoop142/cowin-cli#16]
I've seen that when using the API for listing centers without the token, the data isn't up to date, it takes a little longer to get the centers. Using another script, when using token/adding authorization to the header even for the listing centers/public API, the data is more up to date, it gets the open centers faster.

Do you think you could figure out a way to use the OTP generated token to search as well? Hence simulating a logged-in user?

**Comment by anoop142** [comment]
By default we list  all centers including the ones  that doesn't have any slots left, have you tried with flag '-b' it will show bookable centers(no more fully booked centers.)
I don't think adding token makes it faster or something, i just tested now cowin-cli gets exactly the same data that you get if you login. Adding token for listing results in entering OTP every now and then. 
Maybe other scripts look for today's date?  we always look for tomorrow's date because its not possible to book on the same day as slots are filled the days before.

**Comment by ad1tyas** [comment]
I completely agree that it shouldn't be different. But in practice, it is happening. The notifications that show up on Telegram, etc. show up but the script doesn't see any center.

I verified this just earlier by running the other more known Pallupz script, and yours at the same time. The centers showed up there, but not on this one. The only difference is that the other script uses the token for searching as well.

Maybe you could add it as a flag, so only if a user wants, they can use the token to search.

**Comment by anoop142** [comment]
did the scheduling mode picked up the centers?  or it could be because of any filters, like age or if you are using center_match variable in the bat script? can you confirm this? did you try the list stand alone mode? 'cowin-cli -s state -d district -b' , next time could you try cowin-cli -s state -d district -c dd-mm-yyyy(today's date) -b

**Comment by ad1tyas** [comment]
It's not the scripts fault. It's the way cowin just works. I've noticed that centers show up for people and don't show up for some.

No configuration error from my end.

**Comment by anoop142** [comment]
see edited comment  also you are referring the script to batch/bash script right? maybe the script was sleeping for the time interval 11s? or cowin api actually started  caching data for the request without token

**Comment by ad1tyas** [comment]
It shows the centers mate, just not quick enough. It's because of the token-less request I imagine.

**Comment by anoop142** [comment]
how much delay are we having?

**Comment by ad1tyas** [comment]
Sometimes no delay, sometimes 10 seconds (by then the slots fill up). Sometimes they don't even show up, since the slots are booked out.

**Comment by anoop142** [comment]
11s is the time interval  script does nothing but sleeps , so we don't fill the request limit set by the API. If the slot opens while the script just started sleeping, it won't do anything until the interval is passed , by that time its possible the slot got fully booked. You can decrease the time limit in the script to maybe 8s?

**Comment by ad1tyas** [comment]
It's not a timing thing. It's just the way Cowin works. Sometimes the data is stale, so not really your scripts fault.

If we could get the tokenised search, it will give us the most up to date cowin data.

**Comment by ssmit-b** [comment]
I also have observed the same thing on the Cowin portal itself
one window searching for slots without login(without token)
another window searching for slots with login (with token)
one without login was having stale data

**Comment by ssmit-b** [comment]
> Random Unauthenticated access error for no reasons.

could this be because of same reason?
i don't have conclusive evidence its just a hunch 

@anoop142  have you tried searching for centers after authentication in while loop until the token expires?

**Comment by anoop142** [comment]
> I also have observed the same thing on the Cowin portal itself
> one window searching for slots without login(without token)
> another window searching for slots with login (with token)
> one without login was having stale data

did you use the public search (one without login) to compare?

**Comment by ssmit-b** [comment]
> > I also have observed the same thing on the Cowin portal itself
> > one window searching for slots without login(without token)
> > another window searching for slots with login (with token)
> > one without login was having stale data
> 
> did you use the public search (one without login) to compare?

yes

**Comment by anoop142** [comment]
> > > I also have observed the same thing on the Cowin portal itself
> > > one window searching for slots without login(without token)
> > > another window searching for slots with login (with token)
> > > one without login was having stale data
> > 
> > 
> > did you use the public search (one without login) to compare?
> 
> yes
The public URL isn't same and the data is cached and mostly useless.
