### ISSUE TITLE
OTP not receiving v1.5.4

### ISSUE THREAD

**Issue by TonyStark** [anoop142/cowin-cli#18]
Hi
Affected Version: v1.5.4
Problem: OTP not receiving
--> I have tried two different numbers but i dont get OTP on both number. But on cowin portal everything works perfectly.
So i think maybe api is blocking otp request or something else

**Comment by anoop142** [comment]
I just checked using two numbers, both of the times it worked, make sure the number you passed doesn't have spaces or something?

**Comment by anoop142** [comment]
can you check on 1.5.3

**Comment by TonyStark** [comment]
`I just checked using two numbers, both of the times it worked, make sure the number you passed doesn't have spaces or something?`

> Right now i have tried completely two different number, but still no OTP
> Even i try to change state district, but it cant help
> But using cowin portal i get OTP successfully.
> im using windows 64bit binary with `.bat` file

`can you check on 1.5.3`

> OTP received on both number

**Comment by anoop142** [comment]
there is some weird issue going on with cowin portal rn, otp are actually received but delayed. I'm receiving multiple OTP after i have login using some OTP. I will need some time to figure this out cause I'm using 1.5.4. its working perfectly.

**Comment by anoop142** [comment]
tested by someone else using multiple number, works fine.

**Comment by TonyStark** [comment]
right now using v1.5.5 and it works fine
but still not receive otp using 1.5.4

**Comment by anoop142** [comment]
great.
btw do you also experience centers not detecting or delayed response as #16

**Comment by TonyStark** [comment]
nope never face that error
