### ISSUE TITLE
in bat file there is no option to change date, it books for today. i want to book for tomorrow

### ISSUE THREAD

**Issue by ansi82** [anoop142/cowin-cli#19]

**Comment by anoop142** [comment]
your system's date is correct? cowin-cli always search using tomorrow's date.
You can use the option "-c dd-mm-yyy " to specify a particular date. I'll add a option in the batch script.

**Comment by ansi82** [comment]
system date is correct, sorry for error above. As many hospitals are scheduling day after tomorrow slots and future slots, if we can change the date it would have been great.

**Comment by anoop142** [comment]
fixed 2404d309a1beba6764c9ceaeceea0253a3fb60c8
