### ISSUE TITLE
can you tell me whats wrong in this turmex??

### ISSUE THREAD

**Issue by ansi82** [anoop142/cowin-cli#20]
![WhatsApp Image 2021-05-26 at 11 19 32 PM](https://user-images.githubusercontent.com/84778690/119707655-03dbf880-be79-11eb-9f58-92dd2b78ec96.jpeg)

I have installed all things you have mentioned

**Comment by anoop142** [comment]
did you add GOPATH using the command ?

echo "export GOPATH=$HOME/go\nexport PATH=$PATH:$GOROOT/bin:$GOPATH/bin" >> ~/.bashrc

**Comment by ansi82** [comment]
Yes

**Comment by ansi82** [comment]
Yes, if you want I can do once more and send you pic

**Comment by ansi82** [comment]
> Yes, if you want I can do once more and send you pic

Done bro, needs to do with vpn.
