### ISSUE TITLE
Invalid district!

### ISSUE THREAD

**Issue by sahiliitm** [anoop142/cowin-cli#22]
I am trying to book a slot in south delhi district. Tried "south delhi" "south-delhi" "south_delhi" "southdelhi" but none of them work. How do i figure out the correct district name?

**Comment by anoop142** [comment]
Hi,
it's 'south delhi'. Use cowin.gov.in to get correct name of districts, usually its space separated.

**Comment by sahiliitm** [comment]
Hi, I am unable to make it work.

"./cowin-cli -s delhi -d south delhi  -i -m 18 -v "covaxin" -b -dose 1 -t paid"

It is not working :(

**Comment by anoop142** [comment]
enclose  values that has white spaces in quotes.
