### ISSUE TITLE
Wrong commands and missing code in termux script

### ISSUE THREAD

**Issue by NirmalManoj** [anoop142/cowin-cli#23]
This is a very nice project. Appreciate the effort. I noticed some bugs(I believe they are as I couldn't get them to work) and I am sharing them here.

Notification script for automated termux script isn't available in code. The following line in the termux script should be changed appropriately for termux which I believe is `cowin-cli`
```COWIN_CLI="./cowin-cli"```

schedule function in the termux automated script is the following:
```
schedule(){
	"$COWIN_CLI" -s "$STATE" -d "$DISTRICT" -sc -no "$NO" -names "$NAMES" -centers "$CENTERS" -v "$VACCINE" -dose $DOSE -aotp  -c "$DATE" && exit 0 
}
```
It doesn't have `-m "$AGE"`. But the script for linux have it.

**Comment by NirmalManoj** [comment]
Also, I couldn't install `notify-send`. Would be better if you could provide some more documentation on how to install `notify-send`. For now, what I did was declaring a `notify()` function using `termux-notification`.

```
notify(){
	termux-notification --priority high 
}
```

**Comment by anoop142** [comment]
Hi,
The termux script is kinda outdated , needs update .
 For the notification , we don't need separate system as we have OTP which will notify us.
can you open a pull request ?

**Comment by NirmalManoj** [comment]
@anoop142 Will the termux script work with the changes I mentioned? What happens if a slot time is not given in the termux script? I have been running it for a while now without specifying the slot time.

**Comment by anoop142** [comment]
yeah, I'll push the updated script soon.
It will auto select the first available slot.

**Comment by NirmalManoj** [comment]
Personally, I think it's better to have capabilities for a separate notification with some different vibration pattern and different sound. Because this will make the notification distinct.

As I understand, if the token is still valid, the script won't ask for OTP, right?

**Comment by anoop142** [comment]
When listing ,even if the token isn't valid,  cowin-cli doesn't generate token on its own , because the API is weird , sometimes listing works without token and sometimes even with token it doesn't work at all. 

but for booking we will gen token if current one isn't working.
