### ISSUE TITLE
run this program using termux-api 

### ISSUE THREAD

**Issue by meenachintan90** [anoop142/cowin-cli#24]
I want to run your program whenever i get notification in telegram ... 

Have Tasker 
but don't know how to execute your program via Termux-api

**Comment by anoop142** [comment]
Hi,
I thinks its possible to do something like that, maybe try termux:tasker?  but that's beyond the scope of this project.

**Comment by meenachintan90** [comment]
I somehow managed it to work.. Thank you for your amazing work

**Comment by anoop142** [comment]
It would be nice if you could add the steps followed  for others. Glad it helped :)

**Comment by meenachintan90** [comment]
> It would be nice if you could add the steps followed for others. Glad it helped :)

I'm not a programmer so i can't diagnose problems bht this is what i did

Steps
cowin-cli file in tasker folder

Edits in scripts
COWIN_CLI="cowin-cli" line delete
Next line cd ~/.termux/tasker
Under schedule

"$COWIN_CLI" replaced with cowin-cli




Place cowin-cli in tasker folder 

Open termux

cd ~/.termux/tasker

chmod 777 cowin-cli
