### ISSUE TITLE
Generate Token as a part of executing cowin-cli-notify-book.sh

### ISSUE THREAD

**Issue by jacobgeorge05** [anoop142/cowin-cli#25]
Please advise the steps to be followed to make **Token generation with support for Auto OTP for Token generation** part of executing cowin-cli-notify-book.sh

**Comment by anoop142** [comment]
Hi,
auto otp is only supported when used in termux.
currently there is no need to generate token manually for searching as we are using public url.
Token is generated automatically and prompt user as soon as a center is found, you can manually generate token using token gen mode. refer token generation mode in README.

**Comment by jacobgeorge05** [comment]
I'm running in termux on my phone.

When I run schedule vaccination mode recursively session times out after few iterations. In such cases I have to quit and run token generation manually.

And the  re-execute the script

**Comment by anoop142** [comment]
are you using the latest version? latest doesn't need tokens to search for centers.

**Comment by jacobgeorge05** [comment]
I just updated and now I'm not able to execute the script.

This is what I see

looking for centers..                             cowin-cli v1.7.1 Anoop S
Usage :

List :
  cowin-cli -s state -d district [-v vaccine] [-m age] [-i] [-b] [-c dd-mm-yyyy][-dose dose] [-t freeType] [-ntok] [-public]

Book Vaccine:
  cowin-cli -sc -s state -d district [-no mobileNumber] [-v vaccine] [-m age] [-names name1,name2] [-centers center1,cetner2 ] [-slot slotTime] [-aotp] [-ntok] [-token tokenFile] [-dose dose] [-t freeType] [-public]

Generate Token:
        cowin-cli -gen [-no mobileNumber] [-token tokenFile]

co-cli-test-new.sh: 42: 0: not found
looking for centers..
cowin-cli v1.7.1 Anoop S

**Comment by anoop142** [comment]
Something wrong with your script, use the unedited script.

**Comment by jacobgeorge05** [comment]
Hello Anoop,

Checked out the latest code and script.    

Executing the script, it prints all vaccination centers other than the specific centre I had defined  from the district. follwing the list of centres, it prints **cowin-cli-notify-book.sh : 42:0: not found**

NOTE: I was able to book with same data without script.

Please advise

**Comment by anoop142** [comment]
Hi,
cowin-cli doesn't filter out centers  by it's name, we can only supply centers to auto select if they are available for booking, if you want to filter based on name, edit the CENTER_MATCH, eg : CENTER_MATCH="Kalavoor PHC| Cherthala CHC" and pipe the listing function to grep (  grep -iE "$CENTER_MATCH").
Also i have tested all the scripts no issues at all, can you post the script you are using?

**Comment by jacobgeorge05** [comment]
Please find the script

COWIN_CLI="cowin-cli"

T=5
CENTERS_MATCH='center1|center2|cnter3'
CENTERS="ADUGODI DISPENSARY"
DISTRICT="bbmp"
STATE="karnataka"
AGE=45
NAMES="My Name"
NO="984xxxxxxx"
VACCINE=""
DOSE=1
DATE="08-06-2021"
TYPE=""
SLOT="10:30AM-11:30AM"


schedule(){
	"$COWIN_CLI" -s "$STATE" -d "$DISTRICT" -sc -no "$NO" -names "$NAMES" -m "$AGE" -centers "$CENTERS" -v "$VACCINE" -dose $DOSE   -c "$DATE" -t "$TYPE" -slot "$SLOT" -aotp  && exit 0 
}


while :
do
	echo "looking for centers.."

	"$COWIN_CLI" -s "$STATE"  -d "$DISTRICT" -m "$AGE" -b -v "$VACCINE" -dose $DOSE -c "$DATE" -t "$TYPE"

	if (( $? == 0  )) 
	then
		schedule
	fi

	sleep $T
done`

**Comment by anoop142** [comment]
you don't need to set date tho,leaving it empty  will default to tomorrow's date

**Comment by jacobgeorge05** [comment]
I tried without setting any date.  It is still the same

**Comment by rakeshprabhuvj** [comment]
same error for me. could you please advise the changes requried

**Comment by anoop142** [comment]
I have refactored the scripts , made it more easier to read and modify, check if the problem still exist.

**Comment by jacobgeorge05** [comment]
thanks. it is working now.

**Comment by meenachintan90** [comment]
> I have refactored the scripts , made it more easier to read and modify, check if the problem still exist.

I 

> Hi,
> auto otp is only supported when used in termux.
> currently there is no need to generate token manually for searching as we are using public url.
> Token is generated automatically and prompt user as soon as a center is found, you can manually generate token using token gen mode. refer token generation mode in README.

I have doubt, aren't public url cached and they could be as old as 30 minutes?

We could be getting wrong info about availability of slot..

**Comment by anoop142** [comment]
Yes they are cached , they aren't that old some times, I was able to book using them. but if you want to use protected API you can remove the listing function and call only the booking function.
Each token has a request limit no.  of 20 , additional 100 api request per 5 minutes and some weird too many request restriction.

**Comment by anoop142** [comment]
I have added  an option in the scripts to use the protected API easily
