### ISSUE TITLE
Violation of Govt. Norms

### ISSUE THREAD

**Issue by AnkitGupta17134** [anoop142/cowin-cli#3]
Please delete this repo as it violates guidelines and norms set by gormint of India.

**Comment by anoop142** [comment]
?

**Comment by AnkitGupta17134** [comment]
mera bhi setup krwa de bro.......
idhr aaja - https://meet.google.com/ykg-wivq-meb

**Comment by anoop142** [comment]
can you point out the violations?

**Comment by anoop142** [comment]
This doesn't violate any rules , get your facts checked.
