### ISSUE TITLE
Issue while booking

### ISSUE THREAD

**Issue by nitishpanchpor** [anoop142/cowin-cli#4]
Hi Anoop,
The script is amazing I was able to book an appointment for my mum. But today when I tried to book I received a bad request error.  Also, centre lists do not contain all available centres in districts.

**Comment by anoop142** [comment]
Hey
Are you using the latest version?
bad request error  happens for number of reasons.
1.book for someone under age  45 on 45+ min age limit center.
2. book multiple people with different vaccination status, like one already had first dose , other didn't or having different age limits.

Regarding listing centers
There is a difference between the centers displayed on the cowin website without logging in(the public one) and the list after logging in via otp. cowin-cli list the centers you see after logging in.

**Comment by anoop142** [comment]
Update : They have implemented captcha to book vaccine , so the booking feature no longer works.

**Comment by anoop142** [comment]
Added captcha support. Booking works now!
