### ISSUE TITLE
district name has space

### ISSUE THREAD

**Issue by TonyStark** [anoop142/cowin-cli#6]
lets assume, if district name has space then how to make it work
-d "district name" is not working
example: `-s punjab -d "sas nagar"`
```
$ ./cowin-cli.exe -sc -s punjab -d "sas nagar" -no 90000000
2021/05/11 16:55:10 Invalid district!
```

**Comment by anoop142** [comment]
space is not an issue, just pass them in quotes  like  you did.
it's "SAS Nagar" not "sas nagar". 
Anyway I have added case insensitive checking, now cases doesn't matter.
You can use the  exact command above using the fixed version and  it will work.

**Comment by TonyStark** [comment]
v1.1.1 is working doing -d "SAS Nagar"

**Comment by anoop142** [comment]
v1.1.2 + will work with "sas nagar" , cases are ignored.

**Comment by TonyStark** [comment]
ok thank you :)
