### ISSUE TITLE
suggestion: only one time otp require

### ISSUE THREAD

**Issue by TonyStark** [anoop142/cowin-cli#8]
Hi
Current scenario is:
`Search vaccination center>try to book center>receive OTP>Enter otp>Enter basic Details>Appointment is book OR Vaccination center is full`
If vaccination center is full then we have to follow again same above procedure, and it waste several seconds to book vaccination center because of new otp.
So is that possible that using only one OTP to re-search vaccination center and try to book.
in case vaccination center is full then we dont need to another otp, it just continue recent otp session and book vaccination center.

**Comment by anoop142** [comment]
Feature added.
btw you can pass most of the details in the command itself thus reducing interactive user input.

**Comment by TonyStark** [comment]
one more suggestion to auto solve captcha
ref:https://github.com/ayushchd/cowin_js_bot

**Comment by anoop142** [comment]
auto captcha solve has already added , refer readme.

**Comment by TonyStark** [comment]
oh my bad
i didnt notice :)

**Comment by TonyStark** [comment]
your program works really great, thanks :)
i have one suggestion
is that possible to generate and enter otp before `looking for center` message? then it continue search and booking process

**Comment by anoop142** [comment]
Why?. OTP  takes some time to reach , at least for me, if we wait for it  that time is wasted.

**Comment by anoop142** [comment]
That would make cowin-cli always ask for user input every run , which turns more into a interactive program and after every 15 minutes  the token expires , we have to input otp again. Maybe I could add an option to generate otp and write token.txt, which will be used for booking by default.

**Comment by anoop142** [comment]
token generation mode added , you can use this mode to generate token seperately . If a center is found before the token expires ,this will be used to book the center.

**Comment by TonyStark** [comment]
Hi
Its about v1.5.4
Prob: OTP not receiving
-- I have tried two different numbers but i dont get OTP on both number. But cowin portal works successfull
So i think maybe api is blocking otp request

**Comment by anoop142** [comment]
hi , make new issue
